name: Docker Image CI

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
    
  workflow_call:
    secrets:
      CR_PAT:
        required: true

jobs:
  
  publish-cms-image:
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v2
      
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.CR_PAT }}
      
      - name: build and push the image
        run: |
          docker build . -f ./Dockerfile-push-release --tag ghcr.io/climactivity/cy-cms-2:latest
          docker push ghcr.io/climactivity/cy-cms-2:latest
  
